#!/bin/bash
# Downloading random wallpaper from /wallhaven/ random page
# Dependencies: wget, dos2unix

#Dirs, vars, etc declartion
pdir="$HOME/.ws"
bdir="$pdir/bin"
cdir="$pdir/pics"
slink="http://alpha.wallhaven.cc/search?categories=111&purity=100&sorting=random&order=desc.html"

#Dependencies Check
if [ ! -e /bin/dos2unix ]
    then
     echo "You dont have dos2unix installed, please install it"
fi

if [ ! -e /bin/wget ] 
    then
     echo "You dont have wget installed, please install it"
fi

#Help Function
showhelp(){
    echo "List of available options:

    -n || --nsfw        Run in NSFW mode. (download NSFW wallpapers)
    --taylor-swift      Taylor swift mode.
    -r<resolution>  Search for wallpapers in a specific resolution.
    -h || --help    Show this help message."

}
#Flags
ArgumentCheck(){
    for i in $@; do
        case "$i" in
            -n | --nsfw) echo "Searching for NSFW wallpapers" 
                slink="http://alpha.wallhaven.cc/search?categories=111&purity=010&sorting=random&order=desc.html"
                ;;
            -r*) OUTPUT=`echo $i | sed -e 's/-r//g'`
                echo "Searching for wallpapers with $OUTPUT resolution"
                                  slink="http://alpha.wallhaven.cc/search?categories=111&purity=100&resolutions=$OUTPUT&sorting=random&order=desc.html"
                                  ;;
            --taylor-swift ) echo "TAYLOR SWIFT HYPE"; slink="http://alpha.wallhaven.cc/search?q=taylor%20swift&categories=111&purity=100&sorting=random&order=desc.html";			
                ;;
            -h | --help) showhelp; exit 0
                ;;
            *)  echo "No such flag as "$i""
                showhelp; exit 1
                ;;
        esac
    done
}
ArgumentCheck "$@"
# Checks for the program's data dir and creates it if its missing:
if [ ! -d $pdir ]
  then
	mkdir $pdir
fi

#checks for bin dir and bla bla bla
if [ ! -d $bdir ] 	
	then
  mkdir $bdir
fi

#BLA BLA BLA
if [ ! -d $cdir ]
	then
	mkdir $cdir
fi

# index.html check
if [ -f $pdir/index.html ]
 then
		rm $pdir/index.html
fi

#Downloads the /wallhaven/ page.
wget -q -O $bdir/index.html --directory-prefix=$bdir $slink

#Getting wallpaper's page link
	func1(){
		rand1=$[ ( $RANDOM % 10 ) +1 ] #random in recursive function
		grep "wallpaper/$rand1" "$bdir/index.html" > $bdir/output.txt
		awk '{ print $3 }' $bdir/output.txt > $bdir/awk_output.txt; #THX AWK
		cat $bdir/awk_output.txt | head -1 > $bdir/awk2.txt;
		sed 's/href="//g' $bdir/awk2.txt > $bdir/awk3.txt;
		sed 's/"//g' $bdir/awk3.txt > $bdir/awk4.txt;
		link=$(cat $bdir/awk4.txt);

		if [ ! -s $bdir/output.txt ]
	 	then
				echo "Retrying..."
				sleep 2
			  func1
		fi	
}
func1

#Gets the wallpaper link into var
wget -q "$link" -O $bdir/index.html
grep "full" "$bdir/index.html" > $bdir/output.txt
sed 's/src="//g' $bdir/output.txt > $bdir/output1.txt
sed 's/"//g' $bdir/output1.txt > $bdir/output2.txt
sed 's/ //g' $bdir/output2.txt > $bdir/output4.txt
dos2unix -q $bdir/output4.txt #For this fucking %0D thing, thanks DOS.
link2="http:$(cat $bdir/output4.txt)"


#Downloads the wallpaper (finally)
wget -q "$link2" -P $cdir -A jpg


#Cleanup
rm -r $bdir

#GG
echo "Done, you can find your wallpapers in ~/.ws/pics/"
