#!/bin/bash
# Downloading random wallpaper from /wallhaven/ random page
# Dependencies: wget, dos2unix

#Dirs, vars, etc declartion
pdir="$HOME/.ws"
bdir="$pdir/bin"
cdir="$pdir/pics"
slink="http://alpha.wallhaven.cc/search?categories=111&purity=100&sorting=random&order=desc.html"

#NSFW Filtering
while getopts ":s" args; do 
	case "${args}" in
			s)	
				slink="http://alpha.wallhaven.cc/search?categories=111&purity=010&sorting=random&order=desc.html"
				;;
	esac
		done


# Checks for the program's data dir and creates it if its missing:
if [ ! -d $pdir ]
  then
	mkdir $pdir
fi

#checks for bin dir and bla bla bla
if [ ! -d $bdir ] 	
	then
  mkdir $bdir
fi

#BLA BLA BLA
if [ ! -d $cdir ]
	then
	mkdir $cdir
fi

# index.html check
if [ -f $pdir/index.html ]
 then
		rm $pdir/index.html
fi

#Downloads the /wallhaven/ page.
wget -q -O $bdir/index.html --directory-prefix=$bdir $slink

#Getting wallpaper's page link
	func1(){
		rand1=$[ ( $RANDOM % 10 ) +1 ] #random in recursive function
		grep "wallpaper/$rand1" "$bdir/index.html" > $bdir/output.txt
		awk '{ print $3 }' $bdir/output.txt > $bdir/awk_output.txt; #THX AWK
		cat $bdir/awk_output.txt | head -1 > $bdir/awk2.txt;
		sed 's/href="//g' $bdir/awk2.txt > $bdir/awk3.txt;
		sed 's/"//g' $bdir/awk3.txt > $bdir/awk4.txt;
		link=$(cat $bdir/awk4.txt);

		if [ ! -s $bdir/output.txt ]
	 	then
				echo "Retrying..."
				sleep 2
			  func1
		fi	
}
func1

#Gets the wallpaper link into var
wget -q "$link" -O $bdir/index.html
grep "full" "$bdir/index.html" > $bdir/output.txt
sed 's/src="//g' $bdir/output.txt > $bdir/output1.txt
sed 's/"//g' $bdir/output1.txt > $bdir/output2.txt
sed 's/ //g' $bdir/output2.txt > $bdir/output4.txt
dos2unix -q $bdir/output4.txt #For this fucking %0D thing, thanks DOS.
link2="http:$(cat $bdir/output4.txt)"


#Downloads the wallpaper (finally)
wget -q "$link2" -P $cdir -A jpg


#Cleanup
rm -r $bdir

#GG
echo "Done, you can find your wallpapers in ~/.ws/pics/"
